language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: python manage.py test

services:
  - postgresql

before_install:
  - psql -c "CREATE DATABASE testing_db;" -U postgres